/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetoAlegriaRouteImport } from './routes/projeto-alegria'
import { Route as ProjetosAcessibilidadeRouteImport } from './routes/projetos.acessibilidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoAlegriaRoute = ProjetoAlegriaRouteImport.update({
  id: '/projeto-alegria',
  path: '/projeto-alegria',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosAcessibilidadeRoute = ProjetosAcessibilidadeRouteImport.update({
  id: '/projetos/acessibilidade',
  path: '/projetos/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projeto-alegria': typeof ProjetoAlegriaRoute
  '/projetos/acessibilidade': typeof ProjetosAcessibilidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projeto-alegria': typeof ProjetoAlegriaRoute
  '/projetos/acessibilidade': typeof ProjetosAcessibilidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projeto-alegria': typeof ProjetoAlegriaRoute
  '/projetos/acessibilidade': typeof ProjetosAcessibilidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projeto-alegria' | '/projetos/acessibilidade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projeto-alegria' | '/projetos/acessibilidade'
  id: '__root__' | '/' | '/projeto-alegria' | '/projetos/acessibilidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetoAlegriaRoute: typeof ProjetoAlegriaRoute
  ProjetosAcessibilidadeRoute: typeof ProjetosAcessibilidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto-alegria': {
      id: '/projeto-alegria'
      path: '/projeto-alegria'
      fullPath: '/projeto-alegria'
      preLoaderRoute: typeof ProjetoAlegriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/acessibilidade': {
      id: '/projetos/acessibilidade'
      path: '/projetos/acessibilidade'
      fullPath: '/projetos/acessibilidade'
      preLoaderRoute: typeof ProjetosAcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetoAlegriaRoute: ProjetoAlegriaRoute,
  ProjetosAcessibilidadeRoute: ProjetosAcessibilidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
